imports:
    - { resource: config_dev.yml }

parameters:
    database_name: snaprapid_test

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
        name: snaprapid_test
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
