---
- name: Install PHP CLI
  apt: pkg=php5-cli state=latest update_cache=yes cache_valid_time=3600

- name: Install PHP packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: php_packages

- name: Apply PHP CLI settings
  ini_file: dest=/etc/php5/cli/php.ini section={{ item.section }} option={{ item.option }} value={{ item.value }}
  with_items:
  - "{{ php_cli_default_settings }}"
  - "{{ php_cli_settings }}"
