---
- name: Install php5-fpm
  apt: pkg=php5-fpm state=latest update_cache=yes cache_valid_time=3600

- name: Install PHP packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: php_packages

- name: Remove default pool
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
  notify: restart php5-fpm

- name: Apply PHP FPM settings
  ini_file: dest=/etc/php5/fpm/php.ini section={{ item.section }} option={{ item.option }} value={{ item.value }}
  with_items:
  - "{{ php_fpm_default_settings }}"
  - "{{ php_fpm_settings }}"
  notify: restart php5-fpm

- name: Install pools
  template: src=templates/fpm-pools/{{ item.src }} dest=/etc/php5/fpm/pool.d/{{ item.dest }}
  notify: restart php5-fpm
  with_items: php_fpm_pools
