---
- name: Check if MySQL server installed
  shell: dpkg-query -W -f='${db:Status-Abbrev}' mysql-server || true
  register: mysql_installed

- name: Install MySQL packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb # required by ansible

- name: Stop MySQL if fresh install
  service: name=mysql state=stopped
  when: mysql_installed.stdout != "ii "

- name: Delete InnoDB logs if fresh install # changing logfile size causes restart issue until logs deleted
  shell: rm -f /var/lib/mysql/ib_logfile[01]
  when: mysql_installed.stdout != "ii "

- name: Configure
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0644
  notify: restart mysql

- name: Start MySQL if fresh install
  service: name=mysql state=started
  when: mysql_installed.stdout != "ii "

- name: Set MySQL root password
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Remove anonymous MySQL user
  mysql_user: name='' login_user=root login_password={{ mysql_root_password }} state=absent

- name: Remove MySQL test database
  mysql_db: name=test login_user=root login_password={{ mysql_root_password }} state=absent

- name: Create databases
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  with_items: mysql_databases

- name: Create users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  no_log: true
  with_items: mysql_users
