- name: MongoDB | Fetch GPG key
  sudo: yes
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  tags: mongodb

- name: MongoDB | Add repository
  sudo: yes
  shell:
    echo "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

- name: MongoDB | Install latest mongodb
  sudo: yes
  apt: pkg=mongodb-org update-cache=yes
  tags: mongodb

- name: MongoDB | Run mongo daemon
  sudo: yes
  service: name=mongod state=started
  tags: mongodb

- name: MongoDB | Create database
  mongodb_user: database=admin name={{ mongodb_db_user }} password={{ mongodb_db_pass }} state=present login_port={{ mongodb_port }} roles="root"
